default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.1"
    hooks:
      - id: tox-ini-fmt
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "2.1.3"
    hooks:
      - id: pyproject-fmt
        additional_dependencies: ["tox>=4.9"]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.18.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.4.8'
    hooks:
      - id: ruff
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.28.4
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        alias: format-markdown
        types: [markdown]
        args:
          - --parser=markdown
          - --print-width=88
          - --prose-wrap=always

exclude: |
  (?x)(
    /(
      \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.pytest_cache
      | \.nox
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
    | .*/migrations/.*
  )
