[build-system]
requires = ["setuptools >= 58.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
combine_as_imports = true
skip = "migrations"

[tool.coverage.paths]
source = [
  "src/choicefield",
  "*/.tox/*/lib/*/site-packages/choicefield"
]

[tool.coverage.run]
source = ["choicefield", "tests"]
branch = true
omit = [
  "*/migrations/*",
]

[tool.coverage.report]
skip_covered = true
show_missing = true
exclude_lines = [
  "pragma: no cover",
  # ignore non-implementations
  '^\s*\.\.\.',
  "if TYPE_CHECKING:",
]

[tool.mypy]
python_version = "3.10"
pretty = true
files = "src,tests"
show_error_codes = true

no_implicit_reexport = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = false
local_partial_types = true

warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true

plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "tests.settings"

[[tool.mypy.overrides]]
module = [
  "*.migrations.*",
]
ignore_errors = true

[[tool.mypy.overrides]]
module = [
  "parameterized.*",
]
ignore_missing_imports = true
