# Generated by Django 4.1.1 on 2022-09-22 09:54

import choicefield
from django.db import migrations, models
import tests.test_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_choice', choicefield.ChoiceField(_values=('FIRST', 'SECOND'), enum=tests.test_app.models.TextChoice, max_length=255)),
                ('int_choice', choicefield.ChoiceField(_values=(1, 2), enum=tests.test_app.models.IntChoice)),
            ],
        ),
        migrations.CreateModel(
            name='InlinedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inlined_default', choicefield.ChoiceField(_values=(0,), default=tests.test_app.models.InlinedModel.InlinedEnum['VALUE'], enum=tests.test_app.models.InlinedModel.InlinedEnum)),
                ('inlined_enum', choicefield.ChoiceField(_values=(0,), enum=tests.test_app.models.InlinedModel.InlinedEnum)),
            ],
        ),
        migrations.CreateModel(
            name='NativeEnumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_enum', choicefield.ChoiceField(_values=('A', 'B'), enum=tests.test_app.models.StrEnum, max_length=255)),
                ('int_enum', choicefield.ChoiceField(_values=(3, 4), enum=tests.test_app.models.IntEnum)),
            ],
        ),
        migrations.CreateModel(
            name='NullableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', choicefield.ChoiceField(_values=(1, 2), enum=tests.test_app.models.IntChoice, null=True)),
            ],
        ),
    ]
