name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: less-action/reusables/.github/workflows/pre-commit.yaml@v6
    with:
      python-version: "3.9"

  check-build:
    name: Check packaging
    uses: less-action/reusables/.github/workflows/python-test-build.yaml@v6

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # 3.11
          - python-version: "3.11-dev"
            tox_env: "django41-py311"
          - python-version: "3.11-dev"
            tox_env: "django40-py311"
          # 3.10
          - python-version: "3.10"
            tox_env: "django_main"
          - python-version: "3.10"
            tox_env: "django41-py310"
          - python-version: "3.10"
            tox_env: "django40-py310"
          - python-version: "3.10"
            tox_env: "django32-py310"
          # 3.9
          - python-version: "3.9"
            tox_env: "django41-py39"
          - python-version: "3.9"
            tox_env: "django40-py39"
          - python-version: "3.9"
            tox_env: "django32-py39"
    name: Test ${{ matrix.tox_env }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - name: Run tests
        run: tox -e ${{ matrix.tox_env }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          name: codecov-py${{ matrix.python-version }}

  static-typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install tox
      - name: Run mypy
        run: tox -e mypy

  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install tox
      - name: Check migrations
        run: tox -e check-migrations
